/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.Usuario;
import Factory.Factory;
import Procesos.BaseDatos;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;

/**
 *
 * @author roban
 */
public class Login extends javax.swing.JFrame {

    private static Factory factory;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        factory = new Factory();
        
        /* DECORACIÓN UI */
        
        try
        {
            InputStream is = Login.class.getResourceAsStream("/Resources/OpenSans-Regular.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT, is);
            Font sizedFont = font.deriveFont(16f);
                   
            txt_usuario.setFont(sizedFont);
            txt_contrasena.setFont(sizedFont);
        }
        catch (FontFormatException | IOException ex)
        {
            
        }
        
        txt_usuario.setBorder(null);
        txt_usuario.setOpaque(false);
        txt_usuario.setBackground(new Color(0,0,0,0));
        txt_usuario.setCaretColor(Color.WHITE);
        txt_usuario.setForeground(Color.WHITE);
        
        txt_contrasena.setBorder(null);
        txt_contrasena.setOpaque(false);
        txt_contrasena.setBackground(new Color(0,0,0,0));
        txt_contrasena.setCaretColor(Color.WHITE);
        txt_contrasena.setForeground(Color.WHITE);
        
        btn_aceptar.setOpaque(false);
        btn_aceptar.setContentAreaFilled(false);
        btn_aceptar.setBorderPainted(false);
        
        btn_registrar.setOpaque(false);
        btn_registrar.setContentAreaFilled(false);
        btn_registrar.setBorderPainted(false);
        
        /* FIN DECORACIÓN UI */
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_usuario = new javax.swing.JTextField();
        txt_contrasena = new javax.swing.JPasswordField();
        btn_aceptar = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setMaximumSize(new java.awt.Dimension(1500, 1500));
        setMinimumSize(new java.awt.Dimension(400, 429));
        setPreferredSize(new java.awt.Dimension(400, 429));
        setResizable(false);
        getContentPane().setLayout(null);

        txt_usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txt_usuario);
        txt_usuario.setBounds(88, 147, 250, 26);

        txt_contrasena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txt_contrasena);
        txt_contrasena.setBounds(87, 228, 250, 26);

        btn_aceptar.setBackground(new java.awt.Color(0, 153, 255));
        btn_aceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        btn_aceptar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_aceptar.setOpaque(false);
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_aceptar);
        btn_aceptar.setBounds(20, 300, 170, 50);

        btn_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrar.setOpaque(false);
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrar);
        btn_registrar.setBounds(210, 300, 170, 50);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Login.png"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(1500, 1500));
        Background.setName(""); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 400, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        String user = this.txt_usuario.getText();
        String contrasena = String.valueOf(this.txt_contrasena.getPassword());
        BaseDatos baseDatos = factory.baseDatos();
        boolean aprovada = baseDatos.ValidarLogin(user, contrasena);

        
        
        if (aprovada == true) {
            Usuario userOBJ = baseDatos.obtenerUsuario(user); //A la pantalla principal se la pasa un objeto usuario, para saber quien es el que ha logeado
            System.out.print("Ha sido validado el inicio de sesión");
            Principal principal = factory.principal(userOBJ); //A la GUI principal hay que pasarle un objeto de tipo usuario
            principal.setVisible(true);
            this.dispose();
        } else {
            System.out.print(aprovada + "No se ha sido validado el inicio de sesión");
        }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        RegistroUsuario registroUsuario = factory.registroUsuario();
        registroUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JPasswordField txt_contrasena;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
