/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.*;
import Factory.Factory;
import Procesos.BaseDatos;
import static java.lang.Double.parseDouble;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roban
 */
public class NuevaEntrada extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    static Usuario usuario;
    static String nuevafecha;
    private String descripcion;
    private static Factory factory;

    public NuevaEntrada() {
        initComponents();
        cargarColumnasTabla();
        cargarModeloTabla();
        this.setLocationRelativeTo(null);
        factory = new Factory();
    }

    DefaultTableModel modeloTabla = new DefaultTableModel();

    /*
    Este metodo define las columnas que va a tener la tabla
     */
    private void cargarColumnasTabla() {

        modeloTabla.addColumn("Partida N°");
        modeloTabla.addColumn("Ingreso");
        modeloTabla.addColumn("Egreso");

    }

    private void cargarModeloTabla() {
        DateFormat df = new SimpleDateFormat("dd-MMM-yyyy");
        java.util.Date fecha = new Date();
        int columnas = 1;
        modeloTabla.setNumRows(columnas);
        fechaLB.setText("FECHA: " + df.format(fecha));
        nuevafecha = df.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnG_ingresoEgreso = new javax.swing.ButtonGroup();
        jframe_agregarCuenta = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_nombreCuenta = new javax.swing.JLabel();
        lbl_clasificacion = new javax.swing.JLabel();
        lbl_tipoSaldo = new javax.swing.JLabel();
        btn_agregarCuentaOK = new javax.swing.JButton();
        btn_cancelarCuenta = new javax.swing.JButton();
        txt_nombreCuenta = new javax.swing.JTextField();
        cbox_clasificacionCuenta = new javax.swing.JComboBox<>();
        rbtn_deudor = new javax.swing.JRadioButton();
        rbtn_acreedor = new javax.swing.JRadioButton();
        rbtnG_deudorAcreedor = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_NuevaEntrada = new javax.swing.JTable();
        lbl_cuenta = new javax.swing.JLabel();
        cbox_cuentas = new javax.swing.JComboBox<>();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        lbl_monto = new javax.swing.JLabel();
        montoTXT = new javax.swing.JTextField();
        rbtn_ingreso = new javax.swing.JRadioButton();
        rbtn_egreso = new javax.swing.JRadioButton();
        btn_añadir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionTXT = new javax.swing.JTextArea();
        lbl_descripcion = new javax.swing.JLabel();
        btn_agregarCuenta = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        fechaLB = new javax.swing.JLabel();

        jframe_agregarCuenta.setMinimumSize(new java.awt.Dimension(400, 425));
        jframe_agregarCuenta.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerrarCuadroCuenta(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbl_titulo.setText("Agregar Nueva Cuenta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_titulo)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbl_titulo)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        lbl_nombreCuenta.setText("Nombre de la cuenta");

        lbl_clasificacion.setText("Clasificación");

        lbl_tipoSaldo.setText("Tipo de Saldo");

        btn_agregarCuentaOK.setText("Agregar");
        btn_agregarCuentaOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarCuentaOKActionPerformed(evt);
            }
        });

        btn_cancelarCuenta.setText("Cancelar");
        btn_cancelarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarCuentaActionPerformed(evt);
            }
        });

        cbox_clasificacionCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Pasivo", "Capital", "Ingresos", "Costos", "Gastos" }));

        rbtnG_deudorAcreedor.add(rbtn_deudor);
        rbtn_deudor.setSelected(true);
        rbtn_deudor.setText("Deudor");

        rbtnG_deudorAcreedor.add(rbtn_acreedor);
        rbtn_acreedor.setText("Acreedor");

        javax.swing.GroupLayout jframe_agregarCuentaLayout = new javax.swing.GroupLayout(jframe_agregarCuenta.getContentPane());
        jframe_agregarCuenta.getContentPane().setLayout(jframe_agregarCuentaLayout);
        jframe_agregarCuentaLayout.setHorizontalGroup(
            jframe_agregarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jframe_agregarCuentaLayout.createSequentialGroup()
                .addGroup(jframe_agregarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jframe_agregarCuentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jframe_agregarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombreCuenta)
                            .addComponent(lbl_clasificacion)
                            .addComponent(lbl_tipoSaldo))
                        .addGap(18, 18, 18)
                        .addGroup(jframe_agregarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jframe_agregarCuentaLayout.createSequentialGroup()
                                .addComponent(rbtn_deudor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(rbtn_acreedor))
                            .addComponent(txt_nombreCuenta)
                            .addComponent(cbox_clasificacionCuenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jframe_agregarCuentaLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btn_cancelarCuenta)
                        .addGap(100, 100, 100)
                        .addComponent(btn_agregarCuentaOK)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jframe_agregarCuentaLayout.setVerticalGroup(
            jframe_agregarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_agregarCuentaLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jframe_agregarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombreCuenta)
                    .addComponent(txt_nombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jframe_agregarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_clasificacion)
                    .addComponent(cbox_clasificacionCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jframe_agregarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tipoSaldo)
                    .addComponent(rbtn_deudor)
                    .addComponent(rbtn_acreedor))
                .addGap(18, 18, 18)
                .addGroup(jframe_agregarCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregarCuentaOK)
                    .addComponent(btn_cancelarCuenta))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                focusGained(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                apertura(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Libro Diario: Nueva entrada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1003, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_NuevaEntrada.setModel(modeloTabla);
        jScrollPane1.setViewportView(tabla_NuevaEntrada);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, 983, 299));

        lbl_cuenta.setText("Cuenta");
        jPanel2.add(lbl_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 15, -1, -1));

        cbox_cuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbox_cuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 12, 215, -1));

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(922, 471, -1, -1));

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 471, -1, -1));

        lbl_monto.setText("Monto");
        jPanel2.add(lbl_monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 67, -1, -1));
        jPanel2.add(montoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 64, 215, -1));

        rbtnG_ingresoEgreso.add(rbtn_ingreso);
        rbtn_ingreso.setSelected(true);
        rbtn_ingreso.setText("Ingreso");
        jPanel2.add(rbtn_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 58, -1, -1));

        rbtnG_ingresoEgreso.add(rbtn_egreso);
        rbtn_egreso.setText("Egreso");
        jPanel2.add(rbtn_egreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 58, -1, -1));

        btn_añadir.setText("Agregar");
        btn_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_añadirActionPerformed(evt);
            }
        });
        jPanel2.add(btn_añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 102, -1, -1));

        descripcionTXT.setColumns(20);
        descripcionTXT.setRows(5);
        jScrollPane2.setViewportView(descripcionTXT);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 11, 260, -1));

        lbl_descripcion.setText("Descripción");
        jPanel2.add(lbl_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 13, -1, -1));

        btn_agregarCuenta.setText("+");
        btn_agregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarCuentaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_agregarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 11, -1, -1));

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, 20));

        fechaLB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fechaLB.setText("jLabel2");
        jPanel2.add(fechaLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 102, 250, 26));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarCuentaActionPerformed
        this.jframe_agregarCuenta.setVisible(true);
    }//GEN-LAST:event_btn_agregarCuentaActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_cancelarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarCuentaActionPerformed
        this.jframe_agregarCuenta.setVisible(false);
        BaseDatos base = factory.baseDatos();
        ArrayList<String> tipoCuentas = base.listarCuentas();
        this.cbox_cuentas.removeAllItems();
        for (int i = 0; i < tipoCuentas.size(); i++) {
            this.cbox_cuentas.addItem(tipoCuentas.get(i));
        }
    }//GEN-LAST:event_btn_cancelarCuentaActionPerformed

    private void cargarComboBox() {
        this.jframe_agregarCuenta.setVisible(false);
        BaseDatos base = factory.baseDatos();
        ArrayList<String> tipoCuentas = base.listarCuentas();
        this.cbox_cuentas.removeAllItems();
        for (int i = 0; i < tipoCuentas.size(); i++) {
            this.cbox_cuentas.addItem(tipoCuentas.get(i));
        }
    }

    private void apertura(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_apertura
        BaseDatos base = factory.baseDatos();
        ArrayList<String> tipoCuentas = base.listarCuentas();
        this.cbox_cuentas.removeAllItems();
        for (int i = 0; i < tipoCuentas.size(); i++) {
            this.cbox_cuentas.addItem(tipoCuentas.get(i));
        }
    }//GEN-LAST:event_apertura

    private void btn_agregarCuentaOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarCuentaOKActionPerformed
        String nombreCuenta = this.txt_nombreCuenta.getText();
        String clasificacion = this.cbox_clasificacionCuenta.getSelectedItem().toString();
        String tipoSaldo = null;
        if (this.rbtn_deudor.isSelected()) {
            tipoSaldo = "Deudor";
        } else {
            if (this.rbtn_acreedor.isSelected()) {
                tipoSaldo = "Acreedor";
            }
        }

        Cuenta cuenta = factory.cuenta(nombreCuenta, clasificacion, tipoSaldo, 0);
        BaseDatos baseDatos = factory.baseDatos();
        baseDatos.registrarCuenta(cuenta);
    }//GEN-LAST:event_btn_agregarCuentaOKActionPerformed

    private void cerrarCuadroCuenta(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrarCuadroCuenta
        BaseDatos base = factory.baseDatos();
        ArrayList<String> tipoCuentas = base.listarCuentas();
        this.cbox_cuentas.removeAllItems();
        for (int i = 0; i < tipoCuentas.size(); i++) {
            this.cbox_cuentas.addItem(tipoCuentas.get(i));
        }
    }//GEN-LAST:event_cerrarCuadroCuenta

    private void focusGained(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_focusGained
        this.cargarComboBox();
    }//GEN-LAST:event_focusGained

    private void btn_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_añadirActionPerformed

        //añadir transacion a la tabla
        String cuenta = (String)cbox_cuentas.getSelectedItem(); //accede al tipo de cuenta
        double monto = parseDouble(montoTXT.getText()); //el monto a cargar 
        descripcion = descripcionTXT.getText(); //optiene la descripcion
        boolean lado; //para saber si va en el debe o en el haber
        double debe = 0, haber = 0;
        if(rbtn_ingreso.isSelected()){
            lado = true;
            debe = monto;
        }
        else{
            lado = false;
            haber = monto;
        }
        
        Object filaNueva[] = {cuenta, debe, haber};
        modeloTabla.addRow(filaNueva);
    }//GEN-LAST:event_btn_añadirActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        
        //para validar el debe
        double sumadebe = 0;
        double sumatoria =0;
        //para validar el haber
        double sumahaber =0;
        double sumatoria1 =0;
        
        
        double ingresos, egresos;
        
        //suma toda la columa de los ingresos
        for(int i=1; i<tabla_NuevaEntrada.getRowCount(); i++){
            sumatoria = parseDouble(tabla_NuevaEntrada.getValueAt(i, 1).toString());
            sumadebe += sumatoria;
        }
        ingresos = sumadebe;
        //suma toda la columna de los egresos
        for(int i=1; i<tabla_NuevaEntrada.getRowCount(); i++){
            
            sumatoria1 = parseDouble(tabla_NuevaEntrada.getValueAt(i, 2).toString());
            sumahaber += sumatoria1;
        }
        egresos = sumahaber;
        
        
        if(ingresos == egresos){
            System.out.print("son iguales");
            JOptionPane.showMessageDialog(rootPane, "Cuadran los ingresos y egresos");
            
            Partida partidaOBJ = factory.partida(0 ,factory.baseDatos().idusu, factory.baseDatos().idempre, 3, nuevafecha, descripcion, (float)ingresos, (float) egresos);
            try {
                factory.baseDatos().nuevaPartida(partidaOBJ);
            } catch (SQLException ex) {
                Logger.getLogger(NuevaEntrada.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        else if(ingresos > egresos){
            JOptionPane.showMessageDialog(rootPane, "Son mayores los ingresos");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Son mayores los egresos");
        }
            
        
    }//GEN-LAST:event_btn_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaEntrada.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaEntrada.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaEntrada.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaEntrada.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_agregarCuenta;
    private javax.swing.JButton btn_agregarCuentaOK;
    private javax.swing.JButton btn_añadir;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cancelarCuenta;
    private javax.swing.JComboBox<String> cbox_clasificacionCuenta;
    private javax.swing.JComboBox<String> cbox_cuentas;
    private javax.swing.JTextArea descripcionTXT;
    private javax.swing.JLabel fechaLB;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFrame jframe_agregarCuenta;
    private javax.swing.JLabel lbl_clasificacion;
    private javax.swing.JLabel lbl_cuenta;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_monto;
    private javax.swing.JLabel lbl_nombreCuenta;
    private javax.swing.JLabel lbl_tipoSaldo;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextField montoTXT;
    private javax.swing.ButtonGroup rbtnG_deudorAcreedor;
    private javax.swing.ButtonGroup rbtnG_ingresoEgreso;
    private javax.swing.JRadioButton rbtn_acreedor;
    private javax.swing.JRadioButton rbtn_deudor;
    private javax.swing.JRadioButton rbtn_egreso;
    private javax.swing.JRadioButton rbtn_ingreso;
    private javax.swing.JTable tabla_NuevaEntrada;
    private javax.swing.JTextField txt_nombreCuenta;
    // End of variables declaration//GEN-END:variables
}
