/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.Usuario;
import Factory.Factory;
import Procesos.BaseDatos;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;

/**
 *
 * @author roban
 */
public class RegistroUsuario extends javax.swing.JFrame {

    private static Factory factory;

    /**
     * Creates new form Registro
     */
    public RegistroUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        factory = new Factory();
        
        /* DECORACIÓN UI */
        
        try
        {
            InputStream is = RegistroUsuario.class.getResourceAsStream("/Resources/OpenSans-Regular.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT, is);
            Font sizedFont = font.deriveFont(16f);
                   
            txt_nombres.setFont(sizedFont);
            txt_apellidos.setFont(sizedFont);
            cbox_empresa.setFont(sizedFont);
            txt_usuario.setFont(sizedFont);
            txt_contrasena.setFont(sizedFont);
            txt_correo.setFont(sizedFont);
            txt_telefono.setFont(sizedFont);
            txt_codEmpleado.setFont(sizedFont);
            cbox_rol.setFont(sizedFont);
        }
        catch (FontFormatException | IOException ex) {    }
        
        txt_nombres.setBorder(null);
        txt_nombres.setOpaque(false);
        txt_nombres.setBackground(new Color(0,0,0,0));
        txt_nombres.setCaretColor(Color.WHITE);
        txt_nombres.setForeground(Color.WHITE);
        
        txt_apellidos.setBorder(null);
        txt_apellidos.setOpaque(false);
        txt_apellidos.setBackground(new Color(0,0,0,0));
        txt_apellidos.setCaretColor(Color.WHITE);
        txt_apellidos.setForeground(Color.WHITE);
        
        txt_usuario.setBorder(null);
        txt_usuario.setOpaque(false);
        txt_usuario.setBackground(new Color(0,0,0,0));
        txt_usuario.setCaretColor(Color.WHITE);
        txt_usuario.setForeground(Color.WHITE);
        
        txt_contrasena.setBorder(null);
        txt_contrasena.setOpaque(false);
        txt_contrasena.setBackground(new Color(0,0,0,0));
        txt_contrasena.setCaretColor(Color.WHITE);
        txt_contrasena.setForeground(Color.WHITE);
        
        txt_correo.setBorder(null);
        txt_correo.setOpaque(false);
        txt_correo.setBackground(new Color(0,0,0,0));
        txt_correo.setCaretColor(Color.WHITE);
        txt_correo.setForeground(Color.WHITE);
        
        txt_telefono.setBorder(null);
        txt_telefono.setOpaque(false);
        txt_telefono.setBackground(new Color(0,0,0,0));
        txt_telefono.setCaretColor(Color.WHITE);
        txt_telefono.setForeground(Color.WHITE);
        
        txt_codEmpleado.setBorder(null);
        txt_codEmpleado.setOpaque(false);
        txt_codEmpleado.setBackground(new Color(0,0,0,0));
        txt_codEmpleado.setCaretColor(Color.WHITE);
        txt_codEmpleado.setForeground(Color.WHITE);
        
        btn_registro.setOpaque(false);
        btn_registro.setContentAreaFilled(false);
        btn_registro.setBorderPainted(false);
        
        btn_cancelar.setOpaque(false);
        btn_cancelar.setContentAreaFilled(false);
        btn_cancelar.setBorderPainted(false);
        
        btn_agregarEmpresa.setOpaque(false);
        btn_agregarEmpresa.setContentAreaFilled(false);
        btn_agregarEmpresa.setBorderPainted(false);
        
        /* FIN DECORACIÓN UI */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nombres = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        cbox_empresa = new javax.swing.JComboBox<>();
        txt_usuario = new javax.swing.JTextField();
        btn_agregarEmpresa = new javax.swing.JButton();
        txt_contrasena = new javax.swing.JPasswordField();
        txt_correo = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_codEmpleado = new javax.swing.JTextField();
        cbox_rol = new javax.swing.JComboBox<>();
        btn_cancelar = new javax.swing.JButton();
        btn_registro = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de usuario");
        setMinimumSize(new java.awt.Dimension(528, 796));
        setPreferredSize(new java.awt.Dimension(528, 796));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                apertura(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(txt_nombres);
        txt_nombres.setBounds(158, 213, 290, 20);
        getContentPane().add(txt_apellidos);
        txt_apellidos.setBounds(158, 255, 290, 20);

        getContentPane().add(cbox_empresa);
        cbox_empresa.setBounds(160, 303, 280, 20);
        getContentPane().add(txt_usuario);
        txt_usuario.setBounds(158, 339, 290, 20);

        btn_agregarEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_agregarEmpresa.setOpaque(false);
        btn_agregarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregarEmpresa);
        btn_agregarEmpresa.setBounds(450, 300, 40, 30);
        getContentPane().add(txt_contrasena);
        txt_contrasena.setBounds(158, 387, 290, 20);
        getContentPane().add(txt_correo);
        txt_correo.setBounds(158, 428, 290, 20);
        getContentPane().add(txt_telefono);
        txt_telefono.setBounds(158, 474, 290, 20);
        getContentPane().add(txt_codEmpleado);
        txt_codEmpleado.setBounds(158, 544, 290, 20);

        cbox_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empresario", "Contador", "Auditor" }));
        getContentPane().add(cbox_rol);
        cbox_rol.setBounds(160, 590, 190, 20);

        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.setOpaque(false);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar);
        btn_cancelar.setBounds(291, 682, 220, 60);

        btn_registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registro.setOpaque(false);
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registro);
        btn_registro.setBounds(33, 682, 220, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Registro Usuario.png"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(1500, 1500));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 530, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        Login login = factory.login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed
        BaseDatos baseDatos = factory.baseDatos();
        String nombres;
        String apellidos;
        int empresa;
        String usuario;
        String contrasena;
        String correo;
        int telefono;
        int codEmpleado;
        String rol;

        nombres = this.txt_nombres.getText();
        apellidos = this.txt_apellidos.getText();
        empresa = baseDatos.obtenerEmpresa_SegunNombre(this.cbox_empresa.getItemAt(this.cbox_empresa.getSelectedIndex())).getId();
        usuario = this.txt_usuario.getText();
        contrasena = String.valueOf(this.txt_contrasena.getPassword());
        correo = this.txt_correo.getText();
        telefono = Integer.valueOf(this.txt_telefono.getText());
        codEmpleado = Integer.valueOf(this.txt_codEmpleado.getText());
        rol = this.cbox_empresa.getItemAt(this.cbox_rol.getSelectedIndex());

        Usuario usuarioOBJ = factory.usuario(0, nombres, apellidos, empresa, usuario, contrasena, correo, telefono, codEmpleado, rol);


        baseDatos.registrarUsuario(usuarioOBJ);
    }//GEN-LAST:event_btn_registroActionPerformed

    private void btn_agregarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarEmpresaActionPerformed
        RegistroEmpresa registroEmpresa = factory.registroEmpresa();
        registroEmpresa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_agregarEmpresaActionPerformed

    private void apertura(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_apertura
        BaseDatos base = factory.baseDatos();
        ArrayList<String> listaEmpresas = base.listarEmpresas();
        this.cbox_empresa.removeAllItems();
        for(int i=0; i<listaEmpresas.size(); i++){
             this.cbox_empresa.addItem(listaEmpresas.get(i));
        }
    }//GEN-LAST:event_apertura

    /* Cerrar el formulario hace lo mismo que presionar el botón cancelar para evitar cerrar el programa por completo
    
        -> PROPIEDAD DEL JFRAME CAMBIADA : defaultCloseOperation, de EXIT_ON_CLOSE a DISPOSE.
    */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Login login = factory.login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btn_agregarEmpresa;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_registro;
    private javax.swing.JComboBox<String> cbox_empresa;
    private javax.swing.JComboBox<String> cbox_rol;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_codEmpleado;
    private javax.swing.JPasswordField txt_contrasena;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
