/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.Empresa;
import Factory.Factory;
import Procesos.BaseDatos;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;

/**
 *
 * @author roban
 */
public class RegistroEmpresa extends javax.swing.JFrame {

    private static Factory factory;

    /**
     * Creates new form RegistroEmpresa
     */
    public RegistroEmpresa() {
        initComponents();
        this.setLocationRelativeTo(null);
        factory = new Factory();
        
        try
        {
            InputStream is = RegistroEmpresa.class.getResourceAsStream("/Resources/OpenSans-Regular.ttf");
            Font font = Font.createFont(Font.TRUETYPE_FONT, is);
            Font sizedFont = font.deriveFont(16f);
                   
            txt_nombreEmpresa.setFont(sizedFont);
            txt_formaJuridica.setFont(sizedFont);
            txt_fechaConstitucion.setFont(sizedFont);
            txtA_direccion.setFont(sizedFont);
            txt_correo.setFont(sizedFont);
            txt_numeroRegistro.setFont(sizedFont);
            txt_telefono.setFont(sizedFont);
            txt_dueno.setFont(sizedFont);
            txt_sectorActividad.setFont(sizedFont);
            txtA_resumenNegocio.setFont(sizedFont);
        }
        catch (FontFormatException | IOException ex) {    }
        
        txt_nombreEmpresa.setBorder(null);
        txt_nombreEmpresa.setOpaque(false);
        txt_nombreEmpresa.setBackground(new Color(0,0,0,0));
        txt_nombreEmpresa.setCaretColor(Color.WHITE);
        txt_nombreEmpresa.setForeground(Color.WHITE);
        
        txt_formaJuridica.setBorder(null);
        txt_formaJuridica.setOpaque(false);
        txt_formaJuridica.setBackground(new Color(0,0,0,0));
        txt_formaJuridica.setCaretColor(Color.WHITE);
        txt_formaJuridica.setForeground(Color.WHITE);
        
        txt_fechaConstitucion.setBorder(null);
        txt_fechaConstitucion.setOpaque(false);
        txt_fechaConstitucion.setBackground(new Color(0,0,0,0));
        txt_fechaConstitucion.setCaretColor(Color.WHITE);
        txt_fechaConstitucion.setForeground(Color.WHITE);
        
        txtA_direccion.setBorder(null);
        txtA_direccion.setOpaque(false);
        
        
        txt_correo.setBorder(null);
        txt_correo.setOpaque(false);
        txt_correo.setBackground(new Color(0,0,0,0));
        txt_correo.setCaretColor(Color.WHITE);
        txt_correo.setForeground(Color.WHITE);
        
        txt_numeroRegistro.setBorder(null);
        txt_numeroRegistro.setOpaque(false);
        txt_numeroRegistro.setBackground(new Color(0,0,0,0));
        txt_numeroRegistro.setCaretColor(Color.WHITE);
        txt_numeroRegistro.setForeground(Color.WHITE);
        
        txt_telefono.setBorder(null);
        txt_telefono.setOpaque(false);
        txt_telefono.setBackground(new Color(0,0,0,0));
        txt_telefono.setCaretColor(Color.WHITE);
        txt_telefono.setForeground(Color.WHITE);
        
        txt_dueno.setBorder(null);
        txt_dueno.setOpaque(false);
        txt_dueno.setBackground(new Color(0,0,0,0));
        txt_dueno.setCaretColor(Color.WHITE);
        txt_dueno.setForeground(Color.WHITE);
        
        txt_sectorActividad.setBorder(null);
        txt_sectorActividad.setOpaque(false);
        txt_sectorActividad.setBackground(new Color(0,0,0,0));
        txt_sectorActividad.setCaretColor(Color.WHITE);
        txt_sectorActividad.setForeground(Color.WHITE);
        
        txtA_resumenNegocio.setBorder(null);
        txtA_resumenNegocio.setOpaque(false);
        
        btn_registrar.setOpaque(false);
        btn_registrar.setContentAreaFilled(false);
        btn_registrar.setBorderPainted(false);
        
        btn_cancelar.setOpaque(false);
        btn_cancelar.setContentAreaFilled(false);
        btn_cancelar.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nombreEmpresa = new javax.swing.JTextField();
        txt_fechaConstitucion = new javax.swing.JTextField();
        txt_formaJuridica = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtA_direccion = new javax.swing.JTextArea();
        txt_correo = new javax.swing.JTextField();
        txt_numeroRegistro = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_dueno = new javax.swing.JTextField();
        txt_sectorActividad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_resumenNegocio = new javax.swing.JTextArea();
        btn_registrar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(634, 878));
        setPreferredSize(new java.awt.Dimension(634, 878));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(txt_nombreEmpresa);
        txt_nombreEmpresa.setBounds(308, 222, 290, 20);
        getContentPane().add(txt_fechaConstitucion);
        txt_fechaConstitucion.setBounds(308, 313, 290, 20);
        getContentPane().add(txt_formaJuridica);
        txt_formaJuridica.setBounds(308, 264, 290, 20);

        txtA_direccion.setColumns(1);
        txtA_direccion.setLineWrap(true);
        txtA_direccion.setRows(1);
        jScrollPane2.setViewportView(txtA_direccion);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(310, 350, 290, 60);
        getContentPane().add(txt_correo);
        txt_correo.setBounds(308, 437, 290, 20);
        getContentPane().add(txt_numeroRegistro);
        txt_numeroRegistro.setBounds(308, 479, 290, 20);
        getContentPane().add(txt_telefono);
        txt_telefono.setBounds(308, 521, 290, 20);
        getContentPane().add(txt_dueno);
        txt_dueno.setBounds(308, 564, 290, 20);
        getContentPane().add(txt_sectorActividad);
        txt_sectorActividad.setBounds(308, 606, 290, 20);

        txtA_resumenNegocio.setColumns(1);
        txtA_resumenNegocio.setLineWrap(true);
        txtA_resumenNegocio.setRows(1);
        jScrollPane1.setViewportView(txtA_resumenNegocio);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 653, 290, 90);

        btn_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrar);
        btn_registrar.setBounds(83, 792, 220, 60);

        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar);
        btn_cancelar.setBounds(341, 792, 220, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Registro Empresa.png"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(1500, 1500));
        getContentPane().add(Background);
        Background.setBounds(0, 0, 640, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        RegistroUsuario registroUsuario = factory.registroUsuario();
        registroUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        String nomre_empresa = this.txt_nombreEmpresa.getText();
        String forma_juridica = this.txt_formaJuridica.getText();
        String fecha_constitucion = this.txt_fechaConstitucion.getText();
        String direccion = this.txtA_direccion.getText();
        String correo = this.txt_correo.getText();
        String registro_legal = this.txt_numeroRegistro.getText();
        int telefono = Integer.valueOf(this.txt_telefono.getText());
        String dueno = this.txt_dueno.getText();
        String sector_actividad = this.txt_sectorActividad.getText();
        String resumen_negocio = this.txtA_resumenNegocio.getText();

        Empresa empresaOBJ = factory.empresa(0, nomre_empresa, forma_juridica, fecha_constitucion, direccion, correo, registro_legal, telefono, dueno, sector_actividad, resumen_negocio);

        BaseDatos baseDatos = factory.baseDatos();
        baseDatos.registrarEmpresa(empresaOBJ);

    }//GEN-LAST:event_btn_registrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        RegistroUsuario registroUsuario = factory.registroUsuario();
        registroUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpresa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpresa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpresa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEmpresa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtA_direccion;
    private javax.swing.JTextArea txtA_resumenNegocio;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_dueno;
    private javax.swing.JTextField txt_fechaConstitucion;
    private javax.swing.JTextField txt_formaJuridica;
    private javax.swing.JTextField txt_nombreEmpresa;
    private javax.swing.JTextField txt_numeroRegistro;
    private javax.swing.JTextField txt_sectorActividad;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
